waypoints:
  A:
    x: 1.0
    y: 0.0
    yaw: 0.0
  B:
    x: -0.02
    y: 1.05
    yaw: 0.0
  C:
    x: 0.0
    y: 3.0
    yaw: 0.0
  D:
    x: 3.0
    y: 3.0
    yaw: 0.0

  X:
    x: 100.0
    y: 100.0
    yaw: 0.0